const styles = {
    reviewBox : {
        width: '100%',
        height: 'auto',
        margin: 'auto',
        border: 'solid',
        borderColor: '#D3D3D3',
        borderWidth: 'thin',
        borderRadius: '3px',
        float: 'left',
        fontSize: '16px',
        backgroundColor: 'white',
        boxShadow: '1px 1px #D3D3D3',
        // position: 'relative',
      },
    
    avatarImage : {
        height: '35px',
        width: '35px',
        borderRadius: '50%',
        border: 'solid',
        borderWidth: 'thin',
        borderColor: 'white',
        position: 'relative',
        float: 'left',
        marginTop: '20px',
        marginLeft: '20px',
      },
    
    smallBox : {
        width: '5px',
        height: 'auto',
        border: 'solid',
        borderColor: '#D3D3D3',
        borderWidth: 'thin',
        borderRadius: '3px',
        fontSize: '12px',
        color: '#D3D3D3',
        backgroundColor: 'white',
        marginLeft:'10px',
        position: 'relative',
    
      },
    
    userAndEndorsmentsPlacement : {
        fontSize: '14px', 
        float: 'left',
        postition: 'relative', 
        marginTop: '20px',
        paddingLeft: '10px',
      },
    
    reviewInfo : {
        float: 'left',
        marginLeft: '65px',
        marginRight: '10px',
        // paddingBottom: '15px',
        color: '#5b6a69',
        paddingTop: '40px',
      },
    
    timePlacement : {
        float: 'right',
        marginRight: '10px',
        fontSize: '12px',
        color: '#5b6a69',
        position: 'relative',
        marginTop: '20px',
      },
    
    imageStyle : {
        height: '15px',
        width: '15px',
        backgroundColor: 'white',
        color: '#5b6a69',
      },
    
    buttonStyles : {
        textAlign: 'left',
        background: 'none',
        border: 'none',
        padding: '0',
        marginBottom: '10px',
        marginRight: '20px',
        fontSize: '14px',
        color: '#5b6a69',
        float: 'left',
      },
    submitButtonStyle : {
        textAlign: 'left',
        background: '#14b6ad',
        paddingTop: '6px',
        paddingBottom: '6px',
        paddingLeft: '17px',
        paddingRight: '17px',
        borderRadius: '3px',
        marginBottom: '10px',
        marginRight: '20px',
        fontSize: '14px',
        color: 'white',
        float: 'left',
      },
    cancelButtonStyle : {
        textAlign: 'left',
        background: 'none',
        padding: '10px',
        border: 'none',
        marginBottom: '10px',
        marginRight: '20px',
        fontSize: '14px',
        color: '#5b6a69',
        float: 'left',
      },
      
    dotStyle : {
        textAlign: 'left',
        background: 'none',
        border: 'none',
        padding: '0',
        marginRight: '20px',
        fontSize: '26px',
        color: '#5b6a69',
        float: 'left',
        position: 'relative',
        bottom: '12px',
      },
    
    addFriendStyle : {
        // paddingLeft: '5px',
        height: 'auto',
        width: '35px',
        position: 'relative',
        // bottom: '20px',
        // display: 'inline',
        // marginLeft: '155px',
        top: '8px',
        float: 'left',
      },
    
    starsStyle : {
        float: 'left',
        // marginLeft: '50px',
        // marginRight: '10px',
        position: 'relative',
        top: '50px',
        right: '170px',
      },
      
    smallAvatarImageReplyTo : {
        marginTop: '10px',
        marginLeft: '10px',
        height: '16px',
        width: '16px',
        border: 'solid',
        borderWidth: 'thin',
        borderColor: 'white',
        borderRadius: '50%',
        position: 'relative',
      },
    
    smallDotsBoxStyle : {
        border: 'solid',
        borderColor: '#D3D3D3',
        borderWidth: 'thin',
        borderRadius: '3px',
        fontSize: '12px',
        color: '#D3D3D3',
        backgroundColor: 'white',
        paddingTop: '7px',
        paddingLeft: '15px',
        float: 'left',
        position: 'relative',
        bottom: '40px',
      },
}

export default styles;
